theme: jekyll-theme-cayman
description: The newest RPG by ADHD Games
---


---

<p><strong>Update 03/24/2020</strong><br>
Alpha 0.22 was released<br>
<a href="https://github.com/ADHD-Games/world-of-exorvia/releases/download/v0.22/windows_ver.rar">DIRECT DOWNLOAD</a></p>
<p>There are a few changes in this version.</p>
<ol>
<li>NEW MAPS</li>
</ol>
<p>OVERWORLD MAP<br>
<img src="https://i.imgur.com/PuNyFf3.png" alt="enter image description here"></p>
<p>1st DUNGEON<br>
<img src="https://i.imgur.com/aTO3AUj.png" alt="enter image description here"></p>
<ol start="2">
<li>Added new music</li>
<li>Fixed some bugs</li>
<li>Started testing multi-member party system</li>
</ol>
<p><strong>Well until the next update, This is Jairus, signing out.</strong></p>


